In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.18.5


In [ ]:
arr=np.array([12,3,4,5])
print(arr)
print(type(arr))

[12  3  4  5]
<class 'numpy.ndarray'>


In [ ]:
arr1=np.array((1,2,3,4,5))
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#o-D array
arr=np.array(10)
print(arr)

10


In [ ]:
#1-D array
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
#2-D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3-D array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#checking no. of dimensions in an array using ndim attribute
print(arr.ndim)
print(arr1.ndim)

3
1


In [ ]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [ ]:
arr3=np.array([[1,2,3,4],[1,2]],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


array indexing

In [ ]:
print(arr1[0])
print(arr1[1])
print(arr1[2]+arr1[3])

1
2
7


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr[1,0,2])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
print(arr[0,1,-1])

6
